[package]
name = "email_alias"
version = "0.1.0"
authors = ["\"Spencer Ferris\" <spencer@spencewenski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2"
rand = "0.7"
